spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: /mapper/*.xml

#   port: 9090
#   servlet:
#     context-path: /start